version: '3.1'

services:

  db :
    image: mariadb:10.11
    container_name: sismed
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 12345
      MARIADB_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: sismed
    volumes:
      - "./mariadb-data/data:/var/lib/mysql/data/"
      - "./mariadb-data/logs:/var/lib/mysql/logs/"
    ports:
      - 3306:3306