ALTER TABLE usuario MODIFY id INTEGER UNIQUE NOT NULL AUTO_INCREMENT;
ALTER TABLE usuario MODIFY password VARCHAR(100) NOT NULL;
ALTER TABLE usuario MODIFY login VARCHAR(100) NOT NULL UNIQUE;
ALTER TABLE usuario MODIFY role VARCHAR(20);